version: "0.1"

services:
  materials-mongo:
    build: DataSources/MaterialDB
    container_name: anv-materials-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
  suppliers-mongo:
    build: DataSources/Supplier
    container_name: anv-supplier-db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
  orderreg-mongo:
    build: DataSources/OrderRegistry
    container_name: anv-orderreg-db
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
  datafetch-api:
    build: DataAggregator
    container_name: anv-datafetch-api
    ports:
      - "8132:8000"
    environment:
      MATERIALS_DB_URL: mongodb://admin:toor@anv-materials-db:27017/
      SUPPLIERS_DB_URL: mongodb://admin:toor@anv-supplier-db:27017/
      ORDERS_DB_URL: mongodb://admin:toor@anv-orderreg-db:27017/
  # ahp:
  #   build: AHP
  #   container_name: anv-ahp
  #   ports:
  #     - "8080:8080"
