version: "0.1"

services:
  datafetch-api:
    build: 
      context : .
      dockerfile: Dockerfile.service
    ports:
      - "8132:8000"
    environment:
      MATERIALS_DB_URL: mongodb://admin:toor@materials-db:27017/
      SUPPLIERS_DB_URL: mongodb://admin:toor@supplier-db:27017/
      ORDERS_DB_URL: mongodb://admin:toor@orderreg-db:27017/
    networks:
      - shared
  datafetch-job:
    build: 
      context : .
      dockerfile: Dockerfile.job
    environment:
      MATERIALS_DB_URL: mongodb://admin:toor@materials-db:27017/
      SUPPLIERS_DB_URL: mongodb://admin:toor@supplier-db:27017/
      ORDERS_DB_URL: mongodb://admin:toor@orderreg-db:27017/
    networks:
      - shared
networks:
  shared:
    external: true
    name: anv-net
