FROM python:3.12-slim

WORKDIR /app

COPY requirements_job.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY data.py main.py

# DB connection strings — override at runtime via -e or docker-compose env
ENV MATERIALS_DB_URL=mongodb://admin:toor@localhost:27018/
ENV SUPPLIERS_DB_URL=mongodb://admin:toor@localhost:27019/
ENV ORDERS_DB_URL=mongodb://admin:toor@localhost:27016/


CMD ["python","main.py"]