version: "0.1"

services:
  materials-db:
    build: MaterialDB
    container_name: materials-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - shared
      - default   


  suppliers-db:
    build: Supplier
    container_name: supplier-db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - shared
      - default   
  orderreg-db:
    build: OrderRegistry
    container_name: orderreg-db
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - shared
      - default   
  db-ui:
      image: mongoclient/mongoclient:latest
      ports:
        - "3132:3000"
      volumes:
        - mongoclient-data:/data/db   # persists your saved connections
      depends_on:
        - materials-db
        - suppliers-db
        - orderreg-db

volumes:
  mongoclient-data:

networks:
  shared:
    external: true
    name: anv-net

