version: "0.1"

services:
  materials-mongo:
    build: MaterialDB
    container_name: anv-materials-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
  suppliers-mongo:
    build: Supplier
    container_name: anv-supplier-db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
  orderreg-mongo:
    build: OrderRegistry
    container_name: anv-orderreg-db
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
  mongo-ui:
      image: mongoclient/mongoclient:latest
      ports:
        - "3132:3000"
      volumes:
        - mongoclient-data:/data/db   # persists your saved connections
      depends_on:
        - materials-mongo
        - suppliers-mongo
        - orderreg-mongo

volumes:
  mongoclient-data:
  # ahp:
  #   build: AHP
  #   container_name: anv-ahp
  #   ports:
  #     - "8080:8080"
